### PR TITLE
Fix cell-hiding (#2056)

### LINKED ISSUE #2056: Messages disappear after short long-press
- Messages disappear after long-press them shortly
- Probable reason: `cell.messageBackgroundContainer.isHidden = (reactionsHidden == false)`
- But why isn't it triggered with `false` when canceling the long-press?

simulator_screenshot_CFE99236-CEE8-4EE4-B648-EB5D36C84BE0

### PR DESCRIPTION
**Pull request by zeitschlag**
Closes #2056

### CODE REVIEW

File: deltachat-ios/Chat/ChatViewController.swift [hunk 1]
```diff
@@ -1927,8 +1947,8 @@ class ChatViewController: UITableViewController, UITableViewDropDelegate {
     }
 
 
+
```
Comment (r10s) [inline deltachat-ios/Chat/ChatViewController.swift:1950]: with too many empty lines, we get a "whitespace" warning :)

```suggestion

```

**Review by r10s — APPROVED** [review]
lgtm, also tested, works for me(tm)
