### PR TITLE
fix truncated empty state lables 

### LINKED ISSUE #1009: sometimes truncated "empty" hints
the "no documents" hint may be truncated, depending on screen size and language, here is an example with german on an iphone7/se2:

we should also check if that can happen for the other hints (i am pretty sure, it can :)

### PR DESCRIPTION
**Pull request by cyBerta**
fixes #1009

### CODE REVIEW

File: deltachat-ios/View/FlexLabel.swift [hunk 1]
```diff
@@ -1,84 +0,0 @@
...
-        addSubview(label)
-        label.translatesAutoresizingMaskIntoConstraints = false
-        label.centerYAnchor.constraint(equalTo: centerYAnchor, constant: 0).isActive = true
-        label.centerXAnchor.constraint(equalTo: centerXAnchor, constant: 0).isActive = true
-        label.topAnchor.constraint(equalTo: layoutMarginsGuide.topAnchor).isActive = true
-        label.bottomAnchor.constraint(equalTo: layoutMarginsGuide.bottomAnchor).isActive = true
-        label.widthAnchor.constraint(lessThanOrEqualTo: widthAnchor, multiplier: 0.95).isActive = true
-    }
-
-    ///FIXME: - replace this implementation, it's cutting off long texts, check PaddingTextView
```
Comment (cyBerta) [inline deltachat-ios/View/FlexLabel.swift:59]: there was already a fixme, to replace the old implementation...

**Review by r10s — COMMENTED** [review]
lgtm

**Review by r10s — APPROVED** [review]
