### PR TITLE
Bugfix - qr reader no longer induces crashes on simulators

### LINKED ISSUE #688: On Simulator - app crashes when toggling between qr segments
To reproduce:

On simulator -> qr Tab -> select Qr-Code scan segment -> back to Qr-invitation segment -> back to Qr-Code scan segment -> App freezes + crashs.

I think this has something to do that on Simulators there is no camera access.

### PR DESCRIPTION
**Pull request by nayooti**
fixes #688 

Easiest solution was just to not start the video capture session on simulators.

### CODE REVIEW

File: deltachat-ios/Controller/QrCodeReaderController.swift [hunk 1]
```diff
@@ -95,32 +95,37 @@ class QrCodeReaderController: UIViewController {
...
 
     // MARK: - actions
     func startSession() {
+        #if targetEnvironment(simulator)
+        // ignore if run from simulator
+        #else
         captureSession.startRunning()
-    }
+        #endif
+        }
```
Comment (r10s) [inline deltachat-ios/Controller/QrCodeReaderController.swift:120]: i think this curly bracket is not corrected indented.

File: deltachat-ios/Controller/QrCodeReaderController.swift [hunk 2]
```diff
@@ -95,32 +95,37 @@ class QrCodeReaderController: UIViewController {
...
 
     func stopSession() {
         captureSession.stopRunning()
     }
+
+    @objc private func cameraAccessButtonPressed(_ sender: UIButton) {
+        print("Camera button pressed")
+    }
```
Comment (r10s) [inline deltachat-ios/Controller/QrCodeReaderController.swift:128]: why is that overided now? how is that related to simulator or not?

Comment (nayooti) [reply deltachat-ios/Controller/QrCodeReaderController.swift:128]: forgot to delete.
