### PR TITLE
tweak and fix delivery-state indicator

### LINKED ISSUE #319: delivery-checkmarks must not be shown for incoming messages
the checkmarks for "message sent" (on checkmark) and "message read" must be shown only for outgoing messages, not for incoming messages.

for incoming messages, this place is just empty or may show the number of unread messages.

### PR DESCRIPTION
**Pull request by r10s**
fixes #319

### CODE REVIEW

File: deltachat-ios/Controller/ChatViewController.swift [hunk 1]
```diff
@@ -618,8 +618,24 @@ extension ChatViewController: MessagesDataSource {
             let text = NSMutableAttributedString()
             text.append(NSAttributedString(string: m.formattedSentDate(), attributes: timestampAttributes))
 
+            // TODO: this should be replaced by the respective icons,
+            // for accessibility, the a11y strings should be added
```
Comment (cyBerta) [inline deltachat-ios/Controller/ChatViewController.swift]: also, the state strings should be localized in the future
