### PR TITLE
Fix image message layout

### LINKED ISSUE #685: images are too large in landscape mode
when using the device in landscape mode, landscape-images are shown too large, they might be even larger than the screen.

this happens a lot on ipad-usage - but also on iphone in landscape.

i suggest, to use the calculated-portrait-image sizes for both, landscape and portrait mode.

### PR DESCRIPTION
**Pull request by cyBerta**
closes #685

### CODE REVIEW

File: deltachat-ios/MessageKit/Layout/MediaMessageSizeCalculator.swift [hunk 1]
```diff
@@ -27,15 +27,28 @@ import UIKit
 
 open class MediaMessageSizeCalculator: MessageSizeCalculator {
 
+    var maxMediaItemHeight: CGFloat {
```
Comment (nayooti) [inline deltachat-ios/MessageKit/Layout/MediaMessageSizeCalculator.swift:30]: can be set `private`

File: deltachat-ios/MessageKit/Layout/TextMediaMessageSizeCalculator.swift [hunk 2]
```diff
@@ -27,6 +27,12 @@ import UIKit
 
 open class TextMediaMessageSizeCalculator: MessageSizeCalculator {
 
+    var maxMediaItemHeight: CGFloat {
```
Comment (nayooti) [inline deltachat-ios/MessageKit/Layout/TextMediaMessageSizeCalculator.swift:30]: `private`

File: deltachat-ios/MessageKit/Layout/TextMediaMessageSizeCalculator.swift [hunk 3]
```diff
@@ -27,6 +27,12 @@ import UIKit
...
+        return UIScreen.main.bounds.size.height * 0.8
+    }
+
+    let minTextWidth: CGFloat = 180
```
Comment (nayooti) [inline deltachat-ios/MessageKit/Layout/TextMediaMessageSizeCalculator.swift:34]: `private`

File: deltachat-ios/MessageKit/Layout/TextMediaMessageSizeCalculator.swift [hunk 4]
```diff
@@ -27,6 +27,12 @@ import UIKit
 
 open class TextMediaMessageSizeCalculator: MessageSizeCalculator {
 
+    var maxMediaItemHeight: CGFloat {
+        return UIScreen.main.bounds.size.height * 0.8
```
Comment (nayooti) [inline deltachat-ios/MessageKit/Layout/TextMediaMessageSizeCalculator.swift:31]: On smaller devices in landscape the images still are larger than the screen. Why not use something like this:
Screenheight - NavbarHeight (~44) - InputViewHeight (~100). 
This will never accurate (because inputView does respect safeArea), but this way it is guaranteed  to be smaller than the chat window.

Comment (cyBerta) [reply deltachat-ios/MessageKit/Layout/TextMediaMessageSizeCalculator.swift:31]: yes we can do that. Still it can be that the image is larger than the screenHeight if it has a bad ratio (say 1:8) and text is below. But yor suggestion will fix other cases, +1

Comment (cyBerta) [reply deltachat-ios/MessageKit/Layout/TextMediaMessageSizeCalculator.swift:31]: The problem is that the navigationbar height differs between landscape and portatrait, leading to a unnecessarily small image in landscape if I use a constant subtracted from the screen height. I also wonder if the navigation bar height differs between devices, e.g. iPads and iPhones. I would rather reduce the multiplier a little bit so that the media height keeps being fully relative to the screen size.

Comment (nayooti) [reply deltachat-ios/MessageKit/Layout/TextMediaMessageSizeCalculator.swift]: alright.
