### PR TITLE
always refresh chatlist in background if app became active again

### LINKED ISSUE #1553: chatlist timstamps not updated sometimes
to reproduce:
- ~~send~~ receive? a message
- wait some minutes
- -> after some more minutes, the timestamp still shows "Now" where it should show "10 min" or so

EDIT: i just tried sending, this works as expected. but it happens to me just this morning that a received messages shows "Now" hours later. the message was received in background - maybe there is some condition when adding the timer?

### PR DESCRIPTION
**Pull request by cyBerta**
fixes #1553

### CODE REVIEW

File: deltachat-ios/Controller/ChatListController.swift [hunk 1]
```diff
@@ -250,11 +250,11 @@ class ChatListController: UITableViewController {
     private var isInitial = true
     @objc func applicationDidBecomeActive(_ notification: NSNotification) {
         if navigationController?.visibleViewController == self {
-            if !isInitial {
+            if isInitial {
                 isInitial = false
                 startTimer()
-                refreshInBg()
             }
+            refreshInBg()
```
Comment (r10s) [inline deltachat-ios/Controller/ChatListController.swift:257]: i think `refreshInBg` is too much here, no need to reload the chatlist, this is driven by the events already. it should be sufficient to redraw the cells.

(the bug kind of proves that - applicationDidBecomeActive has never done any update - and the chatlist was always okay in my experience - apart of the timestamps :)

Comment (cyBerta) [reply deltachat-ios/Controller/ChatListController.swift:257]: It's not really affecting the perfomance since the whole thing runs in the background and is even debounced. This is also the same what we currently do in the timer that is started by `startTimer()`, so it's also more consistent right now than calling directly handleChatListUpdate().

Comment (r10s) [reply deltachat-ios/Controller/ChatListController.swift:257]: sure, it does not block ui, but doing an expensive request that costs maybe 2 seconds processor time every 60 seconds will still affect overall performance and resources. and, if the call is not needed, it seems to be worthwhile to avoid it.

if `handleChatListUpdate()` just forces the redraw - what's wrong with calling it? 

@cyBerta  we can also discuss this in an av, i am available today :)

Comment (cyBerta) [reply deltachat-ios/Controller/ChatListController.swift:257]: After reviewing it, the timer registration logic is just wrong

Comment (cyBerta) [reply deltachat-ios/Controller/ChatListController.swift]: > After reviewing it,I realized the timer registration logic is just wrong

fixed with last commit

File: deltachat-ios/Controller/ChatListController.swift [hunk 2]
```diff
@@ -251,10 +251,10 @@ class ChatListController: UITableViewController {
     @objc func applicationDidBecomeActive(_ notification: NSNotification) {
         if navigationController?.visibleViewController == self {
             if !isInitial {
-                isInitial = false
                 startTimer()
-                refreshInBg()
             }
+            handleChatListUpdate()
```
Comment (r10s) [inline deltachat-ios/Controller/ChatListController.swift:256]: i think, the `handleChatListUpdate()` can go back to the `!isInitial` condition - if it is the initial load, things are created correctly anyway, calling `handleChatListUpdate()` explicitly in this case would result in one unneeded update.

File: deltachat-ios/Controller/ChatListController.swift [hunk 3]
```diff
@@ -442,8 +442,16 @@ class ChatListController: UITableViewController {
...
+        if Thread.isMainThread {
+            tableView.reloadData()
+            handleEmptyStateLabel()
+        } else {
+            DispatchQueue.main.async { [weak self] in
+                guard let self = self else { return }
+                self.tableView.reloadData()
+                self.handleEmptyStateLabel()
+            }
+        }
```
Comment (r10s) [inline deltachat-ios/Controller/ChatListController.swift:454]: in a subsequent pr, we can remove the thread-checks for the other calls of `handleChatListUpdate()`.

**Review by r10s — APPROVED** [review]
some minors, also testing the pr, works like expected :)

File: deltachat-ios/Controller/ChatListController.swift (hunk 3 above)
Comment (cyBerta) [reply deltachat-ios/Controller/ChatListController.swift:454]: no, better not, or we would have to add them in the ChatListController used in the Share extension as well.

File: deltachat-ios/Controller/ChatListController.swift (hunk 2 above)
Comment (cyBerta) [reply deltachat-ios/Controller/ChatListController.swift:256]: 🤦 right

File: deltachat-ios/Controller/ChatListController.swift (hunk 3 above)
Comment (r10s) [reply deltachat-ios/Controller/ChatListController.swift:454]: k, then better leave things as is.
