### PR TITLE
fix disappearing email and password strings during account setup

### LINKED ISSUE #825: account name and credentials are deleted if user enters any advanced account settings
When setting up an account, the account name and credentials get deleted if the user enters any settings subscreen from `advanced`. 
Reentering the screen should not generally result in the deletion of the email address and password. 
This issue was probably introduced by the attempt to fix  #615

### PR DESCRIPTION
**Pull request by cyBerta**
fixes #825

### CODE REVIEW

File: deltachat-ios/Controller/AccountSetupController.swift [hunk 1]
```diff
@@ -666,6 +660,8 @@ class AccountSetupController: UITableViewController, ProgressAlertHandler {
                 } else if ui["done"] as! Bool {
                     self.dcContext.maybeStartIo()
                     self.updateProgressAlertSuccess(completion: self.handleLoginSuccess)
+                    self.emailCell.setText(text: nil)
```
Comment (nayooti) [inline deltachat-ios/Controller/AccountSetupController.swift:663]: Why exactly is this needed?

I find it a bit weird to see the credential fields to be cleared right before being redirected.
If the clearing is necessary I think we can clear it in `handleLoginSuccess `, so it will be executed in the completion handler.

**Comment by nayooti** [comment]
Somehow I only get this error on my Main-Device - and not on my Dev-Device.

File: deltachat-ios/Controller/AccountSetupController.swift (hunk 1 above)
Comment (cyBerta) [reply deltachat-ios/Controller/AccountSetupController.swift]: Thanks, it was indeed not needed.

**Comment by r10s** [comment]
this is also tested on some device? :)
