### PR TITLE
Fix contact requests

### LINKED ISSUE #261: reliably update contact requests
Atm. the incoming contact requests are not always shown in the contact requests list. I've tested with an email-address that is not connected to a dc client and doesn't support autocrypt.

### LINKED ISSUE #262: tweak Contact Requests in Chat List
For some reason, I've managed to get an entry `Contact Request` in the Chatlist. It disappeared after switching between the tabs again. Needs more debugging...

### PR DESCRIPTION
**Pull request by r10s**
fixes #262
fixes #261

### CODE REVIEW

File: deltachat-ios/Controller/ChatListController.swift [hunk 1]
```diff
@@ -170,12 +170,30 @@ extension ChatListController: UITableViewDataSource, UITableViewDelegate {
...
         let row = indexPath.row
-        if let chatId = chatList?.getChatId(index: row) {
-            if chatId==DC_CHAT_ID_ARCHIVED_LINK {
-                coordinator?.showArchive()
-            } else {
-                coordinator?.showChat(chatId: chatId)
-            }
+        guard let chatList = chatList else { return }
+        let chatId = chatList.getChatId(index: row)
+        if chatId==DC_CHAT_ID_DEADDROP {
```
Comment (Jikstra) [inline deltachat-ios/Controller/ChatListController.swift]: Please add whitespaces

File: deltachat-ios/Controller/ChatListController.swift [hunk 2]
```diff
@@ -170,12 +170,30 @@ extension ChatListController: UITableViewDataSource, UITableViewDelegate {
...
+            }))
+            alert.addAction(UIAlertAction(title: String.localized("not_now"), style: .default, handler: { _ in
+                dcContact.marknoticed()
+            }))
+            alert.addAction(UIAlertAction(title: String.localized("menu_block_contact"), style: .destructive, handler: { _ in
+                dcContact.block()
+            }))
+            alert.addAction(UIAlertAction(title: String.localized("cancel"), style: .cancel))
+            present(alert, animated: true, completion: nil)
+        } else if chatId==DC_CHAT_ID_ARCHIVED_LINK {
```
Comment (Jikstra) [inline deltachat-ios/Controller/ChatListController.swift]: Same here

**Comment by r10s** [comment]
i asked you to merge, not to comment :)
