### PR TITLE
replace potentially harmful 'unowned' by 'weak'

### LINKED ISSUE #700: stop using unowned
`unowned` references are similar to `weak` optional-references and allow values to become nil at any point in the future.

but unlike `weak`, the `unowned` references are forced-unwrapped at the point where the optional is accessed.

if the accessed optional is nil at that point, the app crashed.

defining a reference as being `unowned`, we give a guarantee that the reference can never become nil during the lifetime it is referenced.

this can be guaranteed by a strong pointer, however, it also can be done easily done wrong. and you have to think over it all the time.

- eg. https://www.hackingwithswift.com/articles/179/capture-lists-in-swift-whats-the-difference-between-weak-strong-and-unowned-references says "You should use unowned very carefully indeed."  
- i grep'd the signal source code, and there is not a single unowned reference.

i am not saying, that we are actually doing things wrong, but we have a few crashes here and there, and a general precaution, we should avoid `unowned` as we avoid `as!` and replace existing `unwrap` by `weak` - which is doable in an hour or so, i just tried it. swift makes it pretty simple to deal with weak pointers.

not using `unwrap` eliminates one source of possible troubles.

wrt losing references, this change does not make a difference as unowned references are handled more or less the same by [arc](https://docs.swift.org/swift-book/LanguageGuide/AutomaticReferenceCounting.html).

### PR DESCRIPTION
**Pull request by r10s**
closes #700

### CODE REVIEW

File: deltachat-ios/Controller/GroupChatDetailViewController.swift [hunk 1]
```diff
@@ -401,21 +401,20 @@ extension GroupChatDetailViewController: UITableViewDelegate, UITableViewDataSou
             !isMemberManagementRow(row: row) &&
             getGroupMemberIdFor(row) != currentUser.id {
             // action set for members except for current user
-            let delete = UITableViewRowAction(style: .destructive, title: String.localized("remove_desktop")) { [unowned self] _, indexPath in
-
-                let contact = self.getGroupMember(at: row)
+            let delete = UITableViewRowAction(style: .destructive, title: String.localized("remove_desktop")) { [weak self] _, indexPath in
+                guard let strongSelf = self else { return }
```
Comment (cyBerta) [inline deltachat-ios/Controller/GroupChatDetailViewController.swift:405]: In swift 4.2 the syntax `guard let self = self else { return } ` was introduced to check if self is nil or not

Comment (cyBerta) [reply deltachat-ios/Controller/GroupChatDetailViewController.swift:405]: personally I like that more than a `strongSelf` variable

File: deltachat-ios/Controller/NewChatViewController.swift [hunk 2]
```diff
@@ -228,19 +228,21 @@ class NewChatViewController: UITableViewController {
         if indexPath.section == sectionContacts {
             let contactId = contactIdByRow(indexPath.row)
 
-            let edit = UITableViewRowAction(style: .normal, title: String.localized("info")) { [unowned self] _, _ in
-                if self.searchController.isActive {
-                    self.searchController.dismiss(animated: false) {
-                        self.showContactDetail(contactId: contactId)
+            let edit = UITableViewRowAction(style: .normal, title: String.localized("info")) { [weak self] _, _ in
+                guard let strongSelf = self else { return }
```
Comment (cyBerta) [inline deltachat-ios/Controller/NewChatViewController.swift:232]: same here

File: deltachat-ios/Controller/WelcomeViewController.swift [hunk 3]
```diff
@@ -14,21 +14,22 @@ class WelcomeViewController: UIViewController, ProgressAlertHandler {
...
-            self.navigationController?.pushViewController(accountSetupController, animated: true)
+            strongSelf.navigationController?.pushViewController(accountSetupController, animated: true)
         }
-        view.onScanQRCode  = { [unowned self] in
+        view.onScanQRCode  = { [weak self] in
             let qrReader = QrCodeReaderController()
             qrReader.delegate = self
-            self.qrCodeReader = qrReader
-            self.navigationController?.pushViewController(qrReader, animated: true)
+            self?.qrCodeReader = qrReader
```
Comment (cyBerta) [inline deltachat-ios/Controller/WelcomeViewController.swift:31]: we can use `guard let self = self else { return }` as well. it is very unlikely that between the first and the second `self?` the reference disappears but still it might make sense to have a common pattern for cases where more than once `self?` is called

Comment (r10s) [reply deltachat-ios/Controller/WelcomeViewController.swift:31]: but even when it disappears, things would be fine. in both cases the QrCodeReaderController would not be pushed.

most usages of [weak self] are one-liners, and i would vote for `self?` where possible to keep things short and readable. this is also the way signal uses (also the stringSelf comes from there)

File: deltachat-ios/Controller/GroupChatDetailViewController.swift (hunk 1 above)
Comment (r10s) [reply deltachat-ios/Controller/GroupChatDetailViewController.swift:405]: copied the strongSelf pattern from signal, did not know `guard let self = self else { return }` is possible - but in, fact, we were already using it at two places :)

yip, i will do a commit that changes that.

ftr, this is the discussion about it https://github.com/apple/swift-evolution/blob/master/proposals/0079-upgrade-self-from-weak-to-strong.md

File: deltachat-ios/Controller/WelcomeViewController.swift (hunk 3 above)
Comment (cyBerta) [reply deltachat-ios/Controller/WelcomeViewController.swift:31]: maybe exact this occourence was not the best example. but there are others in the PR where popping a view controller or calling a callback would not happen while other logic was already happening.

Comment (cyBerta) [reply deltachat-ios/Controller/WelcomeViewController.swift:31]: I also wouldn't do it for oneliners

Comment (r10s) [reply deltachat-ios/Controller/WelcomeViewController.swift]: i agree, it is better to use the guard if self? would be used multiple times, this avoid thinking about what will happen if self disappears in between, you're right.

File: deltachat-ios/Handler/DeviceContactsHandler.swift [hunk 4]
```diff
@@ -85,15 +85,15 @@ class DeviceContactsHandler {
         case .denied:
             contactListDelegate?.accessDenied()
         case .restricted, .notDetermined:
-            store.requestAccess(for: .contacts) { [unowned self] granted, _ in
+            store.requestAccess(for: .contacts) { [weak self] granted, _ in
                 if granted {
                     DispatchQueue.main.async {
-                        self.addContactsToCore()
-                        self.contactListDelegate?.accessGranted()
+                        self?.addContactsToCore()
```
Comment (cyBerta) [inline deltachat-ios/Handler/DeviceContactsHandler.swift:91]: here it's still missing
