### PR TITLE
fix app crash if saved messages chat gets deleted

### LINKED ISSUE #1142: crash when deleting save-messages as the last chat
the app crashes when saved-messages chat is the only chat and that is deleted then.

(the core adds a device message about how the saved-messages chat can be recreated, so there will be one chat again; maybe it is related to that)

### PR DESCRIPTION
**Pull request by cyBerta**
fixes #1142

### CODE REVIEW

File: deltachat-ios/ViewModel/ChatListViewModel.swift [hunk 1]
```diff
@@ -201,13 +201,18 @@ class ChatListViewModel: NSObject, ChatListViewModelProtocol {
...
+        let chat = dcContext.getChat(chatId: chatId)
         dcContext.deleteChat(chatId: chatId)
         updateChatList(notifyListener: false)
         safe_assert(indexToDelete != nil)
-        return indexToDelete ?? -1
+        // Do not return the index of the tableview cell for the selfTalk chat:
+        // Immediately after deleting the chat, a message to the device talk chat gets added.
+        // If the device talk chat was not existing it would be created and added to the table data source.
+        // That case invalidates the index.
+        return chat.isSelfTalk ? nil : indexToDelete
```
Comment (r10s) [inline deltachat-ios/ViewModel/ChatListViewModel.swift:215]: hm, pretty special knowledge :)

i think, however, we're doing far too much here. [dc_delete_chat()](https://c.delta.chat/classdc__context__t.html#ad50eed96a11b113c4080886b2b748ff3) already emits the event DC_EVENT_MSGS_CHANGED that we observe and update the chatlist - neither the updateChatList() a few lines above is needed nor the index return value.

**Comment by r10s** [comment]
i did a mini-pr while testing the things i wrote above - https://github.com/deltachat/deltachat-ios/pull/1183

**Review by r10s — APPROVED** [review]
lgtm - for the skipped animation:

- we do not have animations or pin/unpin/archive, so that skipped animation kind of streamlines things :)  

- we get reduced complexity and removed a bug and potential subsequent bugs (if core decides not to add device message or so)

- i think, if really wanted, we can re-introduce animations in another pr, but then in a more compatible way, maybe by checking for simple changes (delete, swap) on the update-event. but that has no priority currently :)
